root: true
env:
  browser: false
  es6: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2019
  sourceType: module
plugins:
  - "@typescript-eslint"
ignorePatterns:
  - node_modules
  - build
  - jest.config.js

rules:
  "@typescript-eslint/explicit-module-boundary-types": off
