root: true
env:
  browser: false
  es6: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:import/recommended"
  - "plugin:import/typescript"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2019
  sourceType: module
plugins:
  - "@typescript-eslint"
ignorePatterns:
  - node_modules
  - build
  - jest.config.js
rules:
  "@typescript-eslint/explicit-module-boundary-types": off
  "prefer-const": off
  "import/no-unused-modules":
    - 1
    - unusedExports: true
      missingExports: true
      ignoreExports:
        - packages/cdk/src/index.ts
        - packages/cdk/src/test/sampleApp.ts
        # - packages/runtime/src/index.ts
        - '**/*.test.ts'
settings:
  import/ignore:
    - .test.ts$ 
    - node_modules
    - build/
  import/resolver:
    node:
      extensions:
        - .js
        - .ts
      moduleDirectory:
        - node_modules
        - packages/cdk/src
        - packages/runtime/src
