name: Version and Release

on:
  workflow_dispatch:
    inputs:
      newversion:
        description: "Semantic Version Bump Type (major minor patch)"
        required: false
        default: patch
  push:
    - master

env:
  node_version: 15

jobs:
  version_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # fetch full history so things like auto-changelog work properly
          fetch-depth: 0
      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}
          # setting a registry enables the NODE_AUTH_TOKEN env variable where we can set an npm token.  REQUIRED
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm test
      - name: Version and publush to npm
        uses: bcomnes/npm-bump@v1.0.4
        with:
          git_email: mischa@jetbridge.com
          git_username: ${{ github.actor }}
          newversion: ${{ github.event.inputs.newversion }}
          push_version_commit: true # if your prePublishOnly step pushes git commits, you can omit this input or set it to false.
          github_token: ${{ secrets.GITHUB_TOKEN }} # built in actions token.  Passed tp gh-release if in use.
          npm_token: ${{ secrets.NPM_TOKEN }} # user set secret token generated at npm
