name: Version and Release

on:
  push:
    branches:
      - master

env:
  node_version: 16

jobs:
  version_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # fetch full history so things like auto-changelog work properly
          fetch-depth: 0
      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}
          registry-url: "https://registry.npmjs.org"
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: npm run build
      - run: npm test
      - name: Automated Version Bump (Runtime)
        uses: "phips28/gh-action-bump-version@master"
        env:
          PACKAGEJSON_DIR: packages/runtime
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Automated Version Bump (CDK)
        uses: "phips28/gh-action-bump-version@master"
        env:
          PACKAGEJSON_DIR: packages/cdk
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish (CDK)
        run: npm publish -w @jetkit/cdk
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish (Runtime)
        run: npm publish -w @jetkit/cdk-runtime
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
